/*
	SST_NetResult.h
	Author: Chris Ertel <crertel@762studios.com>
	Created: 7/12/2012

	Purpose: 

	Possible results from calling libsst-net functions

	License:

	This program is free software. It comes without any warranty, to
	the extent permitted by applicable law. You can redistribute it
	and/or modify it under the terms of the Do What The Fuck You Want
	To Public License, Version 2, as published by Sam Hocevar. See
	http://sam.zoy.org/wtfpl/COPYING for more details.

*/

#pragma once

#ifndef _SST_NETRESULTCODES_H
#define _SST_NETRESULTCODES_H

typedef enum SST_NetResult
{
	SSTNETRESULT_SUCCESS,				/* SUCCESS! HUZZAH! */

	SSTNETRESULT_ACCESSDENIED,			/* WSAEACCES, EACCES */
	SSTNETRESULT_ADDRINUSE,				/* WSAEADDRINUSE, EADDRINUSE */
	SSTNETRESULT_ADDRNOTAVAILABLE,		/* WSAEADDRNOTAVAIL, EADDRNOTAVAIL */
	SSTNETRESULT_ADDRFAMNOTSUPPORTED,	/* WSAEAFNOTSUPPORT, EAFNOSUPPORT */
	SSTNETRESULT_ALREADYCONNECTED,		/* WSAEISCONN, EISCONN */
	SSTNETRESULT_ALREADYCONNECTING,		/* WSAEINPROGRESS, EINPROGRESS */

	SSTNETRESULT_BADPOINTER,			/* WSAEFAULT, EFAULT */
	SSTNETRESULT_BADADDRESSSTRING,		/* Address string was malformed. */
	SSTNETRESULT_BADPROTOCOLLEVEL,		/* Unsupported protocol level given for get/setsockopt. */
	SSTNETRESULT_BADSOCKETOP,			/* Unsupport socket operation given for get/setsockopt. */

	SSTNETRESULT_CONNECTIONABORTED,		/* WSAECONNABORTED, EPIPE */
	SSTNETRESULT_CONNECTIONREFUSED,		/* WSAECONNREFUSED, ECONNREFUSED */
	SSTNETRESULT_CONNECTIONRESET,		/* WSAECONNRESET, ECONNRESET */

	SSTNETRESULT_HOSTUNREACHABLE,		/* WSANO_RECOVERY, WSAEHOSTUNREACH, WSAHOST_NOT_FOUND, EHOSTUNREACH, EAI_FAIL */

	SSTNETRESULT_INTERRUPTED,			/* WSAEINTR, EINTR */
	SSTNETRESULT_INPROGRESS,			/* WSAEINPROGRESS */
	SSTNETRESULT_INVALIDARGS,			/* WSAEINVAL, EINVAL, EAI_BADFLAGS */

	SSTNETRESULT_MESSAGESIZE,			/* WSAEMSGSIZE, EMSGSIZE */

    SSTNETRESULT_NETNOTINIT,			/* WSANOTINITIALISED, WSAEPROVIDERFAILEDINIT */
    SSTNETRESULT_NETDOWN,				/* WSAENETDOWN */
    SSTNETRESULT_NETRESET,				/* WSAENETRESET, ENETRESET */
    SSTNETRESULT_NETUNREACHABLE,		/* WSAENETUNREACH, ENETUNREACH */
    SSTNETRESULT_NODESTADDRESSGIVEN,	/* WSAEDESTADDRREQ */
	SSTNETRESULT_NOFILESAVAILABLE,		/* WSAEMFILE, EMFILE, ENFILE */
	SSTNETRESULT_NOSPACE,				/* WSA_NOT_ENOUGH_MEMORY, WSAENOBUFS, ENOBUFS, ENOMEM */
	SSTNETRESULT_NOTASOCKET,			/* WSAENOTSOCK, ENOTSOCK */
	SSTNETRESULT_NOTBOUND,				/* WSAEINVAL, EDESTADDRREQ */
	SSTNETRESULT_NOTCONNECTED,			/* WSAENOTCONN, ENOTCONN */

	SSTNETRESULT_OPNOTSUPPORTED,		/* WSAEOPNOTSUPP, */

	SSTNETRESULT_PROTOCOLNOTSUPPORTED,	/* WSAEPROTONOSUPPORT, EPROTONOSUPPORT */
	SSTNETRESULT_PROTOCOLOPNOTSUPPORED,	/* WSAENOPROTOOPT , ENOPROTOOPT */

	SSTNETRESULT_SERVICENOTSUPPORTED,	/* 	WSATYPE_NOT_FOUND */
	SSTNETRESULT_SOCKETNOTSUPPORTED,	/* WSAESOCKTNOSUPPORT */
	SSTNETRESULT_SOCKETSHUTDOWN,		/* WSAESHUTDOWN */
	
	SSTNETRESULT_TIMEDOUT,				/* WSAETIMEDOUT, ETIMEDOUT */
	SSTNETRESULT_TRYAGAIN,				/* WSATRY_AGAIN, EAGAIN */

	SSTNETRESULT_WOULDBLOCK,			/* WSAEWOULDBLOCK, EWOULDBLOCK, EAGAIN */
	SSTNETRESULT_WRONGPROTOCOLFORSOCK,	/* WSAEPROTOTYPE, EPROTOTYPE */

	SSTNETRESULT_UNKNOWN,				/* An unkonwn error has occured. */

	SSTNETRESULT_MAX
} SST_NetResult;

#endif